[package]
name = "it"
version = "0.1.0"
edition = "2018"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[features]
default = ["migrate-structures"]
migrate-structures = ["fs_extra"]

[dependencies]
relative-path = {version = "1.0.0", features = ["serde"]}
rayon = "1.3.0"
anyhow = "1.0.31"
thiserror = "1.0.20"
walkdir = "2.3.1"
serde = {version = "1.0.111", features = ["derive"]}
serde_json = "1.0.53"
serde_yaml = "0.8.13"
diff = "0.1.12"
log = "0.4.8"
env_logger = "0.7.1"
handlebars = "3.1.0"
tokio = {version = "0.2.21", features = ["full"]}
futures = "0.3.0"
rand = "0.7.3"
unicode-width = "0.1.7"
memchr = "2.3.3"
num_cpus = "1.13.0"
humantime-serde = "1.0.0"

fs_extra = {version = "1.1.0", optional = true}

[target.'cfg(windows)'.dependencies]
dunce = "1.0.1"

[target.'cfg(unix)'.dependencies]
users = "0.10"