[package]
name = "reproto-it"
version = "0.1.0"
authors = ["John-John Tedro <udoprog@tedro.se>"]

[dependencies]
relative-path = "0.3.7"
rayon = "1.0.2"
failure = "0.1.2"
walkdir = "2.2.0"
serde = "1.0.71"
serde_json = "1.0.26"
serde_derive = "1.0.71"
diff = "0.1.11"

[[bin]]
name = "it"
path = "main.rs"

[lib]
name = "it"
path = "lib.rs"
