[package]
name = "reproto-server"
version = "0.3.37"
authors = ["John-John Tedro <udoprog@tedro.se>"]
license = "MIT/Apache-2.0"
readme = "README.md"
repository = "https://github.com/reproto/reproto"
homepage = "https://github.com/reproto/reproto"
documentation = "https://docs.rs/reproto-server"
description = """
reproto repository server
"""

[features]
# Enable to emit very detailed tracing, potentially performance sensitive.
tracing = []

[dependencies]
reproto-repository = {path = "../lib/repository", version = "0.3"}
reproto-core = {path = "../lib/core", version = "0.3"}

futures = "0.1"
futures-cpupool = "0.1"
hyper = "0.11"
pretty_env_logger = "0.1"
log = "0.3"
tempfile = "2.1"
flate2 = "0.2"
clap = "2.24"
toml = "0.4"
serde = "1.0"
serde_derive = "1.0"
